// Suche alle Fahrzeuge
GET {{baseUrl}}/api
Accept: application/hal+json
Authorization: Basic admin p

###

// Suche alle Fahrzeuge
GET {{baseUrl}}/api
Accept: application/hal+json

###

// Suche alle Fahrzeuge mit falschem Passwort: 401 (Unauthorized)
GET {{baseUrl}}/api
Authorization: Basic {{userAdmin}} {{passwordFalsch}}

###

// Suche alle Fahrzeuge mit fehlenden Rechten: 403 (Forbidden)
GET {{baseUrl}}/api
Authorization: Basic {{userKunde}} {{password}}

###

// Suche mit vorhandener Fahrzeug-ID als admin
//curl --verbose --basic --user admin:p --header "Accept: application/hal+json" --insecure http://kubernetes.docker.internal/kunden/api/00000000-0000-0000-0000-000000000001
//curl --verbose --basic --user admin:p --header "Accept: application/hal+json" --http2 --tlsv1.3 --insecure https://kubernetes.docker.internal/kunden/api/00000000-0000-0000-0000-000000000001
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000000
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###


GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000000
Accept: application/hal+json

###

// Suche mit ungueltiger Fahrzeug-ID
GET {{baseUrl}}/api/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY
Accept: application/hal+json

###

// Suche mit nicht-vorhandener Fahrzeug-ID
GET {{baseUrl}}/api/99999999-9999-9999-9999-999999999999
Accept: application/hal+json

###

// Suche mit falschem Passwort: 401 (Unauthorized)
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
Authorization: Basic Basic {{userAdmin}} {{passwordFalsch}}

###

// Suche mit vorhandener Fahrzeug-ID als kunde
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000000
Accept: application/hal+json
Authorization: Basic {{userKunde}} {{password}}

###

// Suche mit fehlender Berechtigung: 403 (Forbidden)
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000002
Accept: application/hal+json
Authorization: Basic {{userKunde}} {{password}}

###

// Suche mit vorhandener Fahrzeug-ID und ETag
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
If-None-Match: "0"
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandener Fahrzeug-ID und falschem ETag: 406 (Not Acceptable)
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
If-None-Match: 0
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit Teilstring fuer vorhandener beschreibung
GET {{baseUrl}}/api?beschreibung=i
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandener beschreibung
GET {{baseUrl}}/api?beschreibung=Admin
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandenem kennzeichen
GET {{baseUrl}}/api?kennzeichen=KA N 0
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit nicht-vorhandenem kennzeichen
GET {{baseUrl}}/api?kennzeichen=NICHT%40VORHAN.DEN
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandenem (Teil-) Beschreibung und Nachname
GET {{baseUrl}}/api?beschreibung=a&vorname=H
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandenem (Teil-) Beschreibung und Nachname
GET {{baseUrl}}/api?beschreibung=a&nachname=P
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandenem (Teil-) Beschreibung Nachname und Vorname
GET {{baseUrl}}/api?beschreibung=a&vorname=H&nachname=P
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche mit vorhandenem (Teil-) Beschreibung und Fahrzeugtyp
GET {{baseUrl}}/api?beschreibung=a&fahrzeugtyp=P
Accept: application/hal+json
Authorization: Basic {{userAdmin}} {{password}}

###

// Suche Beschreibung mit Praefix
GET {{baseUrl}}/api/beschreibung/A
Accept: text/plain
Authorization: Basic {{userAdmin}} {{password}}
