// Einen Kunden mittels PUT aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/fahrzeug-30-put.json

###


// Ein Fahrzeug mittels PUT aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/fahrzeug-put-webserver.json

###

// Ein Fahrzeug mittels ungueltigem PUT aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/fahrzeug-put-webserver-invalid.json

###

// Einen Kunden mittels PUT und ungueltigen Daten aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/fahrzeug-30-put-invalid.json

###

// Einen Kunden mittels PUT ohne Versionsnummer aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/fahrzeug-30-put.json

###

// Einen Kunden mittels PUT mit alter Versionsnummer aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
If-Match: "-1"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{password}}

< data/fahrzeug-30-put.json

###

// Einen Kunden mittels PUT und falschem Passwort aktualisieren: 401 (Unauthorized)
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000030
If-Match: "0"
Content-Type: application/json
Authorization: Basic {{userAdmin}} {{passwordFalsch}}

< data/fahrzeug-30-put.json
