' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml KundeHandler

skinparam classAttributeIconSize 0

package org.springframework {
    package web.bind.annotation {
        interface "@PathVariable" as PathVariable
        interface "@RequestParam" as RequestParam
    }

    package http {
        class ResponseEntity<T>
        package server.reactive {
            interface ServerHttpRequest
        }
    }
    package hateoas {
        class CollectionModel<E>
    }
}

package java.security {
    interface Principle
}

package com.acme.kunde {
    package entity {
        class Kunde << entity >>
        class KundeId << typealias >>
    }

    package service {
        class KundeService << control >> << @Service >>
    }

    package rest #DDDDDD {
        class KundeModel <<entity>>

        class KundeGetController << boundary >> << @RestController >> << @RequestMapping >> {
            + @GetMapping suspend findById(@PathVariable id: KundeId, @RequestHeader("If-None-Match") version: String, request: ServerHttpRequest, principal: Principal): ResponseEntity<KundeModel>
            + @GetMapping suspend find(@RequestParam queryParams: MultiValueMap<String, String>, request: ServerHttpRequest): ResponseEntity<CollectionModel<KundeModel>>
        }

        KundeGetController o-right-> "1" KundeService : service
        KundeGetController ..> KundeModel
        KundeGetController ..> Kunde
        KundeGetController ..> KundeId

        KundeGetController .up.> CollectionModel
        KundeGetController .up.> ServerHttpRequest

        KundeGetController .up.> PathVariable
        KundeGetController .up.> RequestParam

        KundeGetController .up.> Principle
    }
}

hide empty members

footer (c) Juergen Zimmermann

@enduml
