' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.
@startuml Kunde

skinparam classAttributeIconSize 0
' skinparam monochrome true

package java {
    package util {
        class URL
        class Currency
    }

    package math {
        class BigDecimal
    }

    package time {
        class LocalDate
        class LocalDateTime
    }
}

package com.acme.kunde {
    package entity #DDDDDD {
        class KundeId << typealias >>
        class DbId << typealias >>

        class Umsatz {
            @Id @GeneratedValue @JsonIgnore readonly id : DbId?
            readonly betrag: BigDecimal
            readonly waehrung: Currency
        }
        Umsatz ..> DbId

        class Adresse {
            @Id @GeneratedValue @JsonIgnore readonly id : DbId?
            readonly plz: String
            readonly ort: String
        }
        Adresse ..> DbId

        enum GeschlechtType {
            MAENNLICH
            WEIBLICH
            DIVERS
        }

        enum FamilienstandType {
            LEDIG
            VERHEIRATET
            GESCHIEDEN
            VERWITWET
        }

        enum InteresseType {
            SPORT
            LESEN
            REISEN
        }

        class Kunde << entity >> {
            @Id @GeneratedValue readonly id : KundeId?
            @Version readonly version : Int
            nachname : String
            email : String
            kategorie: Int
            newsletter : Boolean
            geburtsdatum: LocalDate
            homepage: URL
            @Convert geschlecht: GeschlechtType
            @Convert familienstand: FamilienstandType
            @ElementCollection(fetch = EAGER) @CollectionTable @Column @Convert readonly interessen: Set<InteresseType>
            username: String
            @CreationTimestamp readonly erzeugt: LocalDateTime
            @UpdateTimestamp readonly aktualisiert: LocalDateTime
        }

        Kunde *-up-> "1" Umsatz : @OneToOne(cascade = [...]) @JoinColumn(...) umsatz
        Kunde *-up-> "1" Adresse :  @OneToOne(cascade = [...]) @JoinColumn(...) adresse

        Kunde ..> KundeId
        Kunde ..> GeschlechtType
        Kunde ..> FamilienstandType
        Kunde ..> InteresseType
        Kunde ..> URL
        Kunde ..> LocalDate
        Kunde ..> LocalDateTime

        Umsatz ..> Currency
        Umsatz ..> BigDecimal
    }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
